# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

pool:
  vmImage: 'ubuntu-16.04'

steps:

  - script: docker build -t alaskapocregistry.azurecr.io/flight:$(Build.BuildId) .
    displayName: "Building Container"

  - script: |
          docker login -u alaskapocregistry -p ebQ9rlcF+/WddEUc/Fk0ysm/05wJJk+o alaskapocregistry.azurecr.io
          docker push alaskapocregistry.azurecr.io/flight:$(Build.BuildId)
    displayName: "Publishing Container"
